apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.cluster-ttbjw.ttbjw.sandbox2065.opentlc.com/rhtap/test-go:631ba176982e67805fe076560654ce60150f0e6c@sha256:06f0c205ef2fc6cc844efb3d1a1ae2fb7d7dd3b2610fb4caa153d0060e4a2ba7
          name: container-image
