apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-go1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.cluster-qdkvb.qdkvb.sandbox2367.opentlc.com/rhtap/test-go:bad3988035f105aebafb95f6e075d30c244b79b2@sha256:ecabd64a9ec26d44d466380eb3735364c3bfd01b5b24a87cb1cfcf1de3fdc79a
          name: container-image
